### ISSUE TITLE
Accessing the user admin page when no measures are uploaded causes the users to not load

### ISSUE THREAD

**Issue by okeefm** [MeasureAuthoringTool/bonnie#800]
When I try to access `http://localhost:3000/#admin/users` on my development machine, with my user, one other user and no measures in the system, I get the following error from the AJAX request:

```Started GET "/admin/users" for 127.0.0.1 at 2017-07-20 16:26:22 -0400
Processing by Admin::UsersController#index as JSON
MONGODB | localhost:27017 | bonnie_development.find | STARTED | {"find"=>"users", "filter"=>{"_id"=>BSON::ObjectId('59711027e406e80c10b72fa9')}, "limit"=>1, "singleBatch"=>true}
MONGODB | localhost:27017 | bonnie_development.find | SUCCEEDED | 0.00106s
MONGODB | localhost:27017 | bonnie_development.find | STARTED | {"find"=>"users", "filter"=>{}, "sort"=>{"email"=>1}}
MONGODB | localhost:27017 | bonnie_development.find | SUCCEEDED | 0.001029s
MONGODB | localhost:27017 | bonnie_development.mapreduce | STARTED | {"mapreduce"=>"draft_measures", "map"=>"function() { emit(this.user_id, 1); }", "reduce"=>"function(user_id, counts) { return Array.sum(counts); }", "query"=>{}, "out"=>{:inline=>true}}
MONGODB | localhost:27017 | bonnie_development.mapreduce | FAILED | ns doesn't exist () | 0.000413s
Completed 500 Internal Server Error in 7ms

Mongo::Error::OperationFailure (ns doesn't exist ()):
  app/controllers/admin/users_controller.rb:15:in `each_with_object'
  app/controllers/admin/users_controller.rb:15:in `index'


  Rendered /Users/mokeefe/.rvm/gems/ruby-2.3.3/gems/actionpack-4.2.8/lib/action_dispatch/middleware/templates/rescues/_source.erb (2.6ms)
  Rendered /Users/mokeefe/.rvm/gems/ruby-2.3.3/gems/actionpack-4.2.8/lib/action_dispatch/middleware/templates/rescues/_trace.text.erb (0.6ms)
  Rendered /Users/mokeefe/.rvm/gems/ruby-2.3.3/gems/actionpack-4.2.8/lib/action_dispatch/middleware/templates/rescues/_request_and_response.text.erb (0.9ms)
  Rendered /Users/mokeefe/.rvm/gems/ruby-2.3.3/gems/actionpack-4.2.8/lib/action_dispatch/middleware/templates/rescues/diagnostics.text.erb (54.6ms)```

It looks as though this error is caused because there are no Measures/Records uploaded into Bonnie? Uploading a Measure and creating a (mostly blank) Record fixes this.

**Comment by hossenlopp** [comment]
Did you run `bundle exec db:setup`?

**Comment by okeefm** [comment]
I didn't, the installation instructions I was following didn't say to: https://github.com/projecttacoma/bonnie/wiki/Installation-Instructions

**Comment by okeefm** [comment]
Just tried running that on a fresh DB; that fixed it.

**Comment by hossenlopp** [comment]
Step has been added in installation instructions. It actually is a rake task `bundle exec rake db:setup` and then add `RAILS_ENV=production` if needed.
